### ISSUE TITLE
unable to install on R v3.5.0

### ISSUE THREAD

**Issue by nahuron** [sjbeckett/FALCON#1]
Hello! I am interested in trying to using FALCON for some of my own data. Whether by my own fault or something else, I have been unable to install it with R v3.5.0. I have tried `install_github()` as well as downloading it and trying to install it locally with `install.packages()`. Could you help point me in the right direction? Thanks!

**Comment by sjbeckett** [comment]
Hi Nicholas, I must admit that I have never tried to use the code using either of these procedures, so I am not sure exactly why they fail. It is most likely my code is not in the correct format to be installed as a package.

However, you should still be able to use the code in FALCON, by downloading the files. Then in R, you can run  `source("PATH/FALCON/R/PERFORM_NESTED_TEST.R")`  where PATH is the path from your working directory to the FALCON folder. Hope this helps, please let me know how you get on!

**Comment by nahuron** [comment]
Stephen,

Thank you for the pointer! I will give it a shot.

Cheers,

Nick

Nicholas A. Huron
Graduate Student in Biology, Temple University
B.S. Biology, Pepperdine University
nicholashuron.com <http://nicholashuron.strikingly.com/>
